### ISSUE TITLE
Throwing error after backup of 50 users

### ISSUE THREAD

**Issue by RSingholia** [smartsheet-platform/backup-java#12]
Please see the attached and suggest how to resolve this error.

![smartsheet backup error](https://cloud.githubusercontent.com/assets/16663546/16907614/9c28f330-4ce2-11e6-8684-17434b25cbba.png)

**Comment by avioing** [comment]
The errors you are seeing are normal and by design - looks like you are
trying to back up users who have never logged into Smartsheet.  If they
never logged in, they never accepted our terms of use.  Without that, you
won't be able to issue any API commands as those users (which is what the
backup tool is trying to do).

To can bypass this error by setting *continueOnError* paramater to true.
See our backup docs https://github.com/smartsheet-platform/backup-java
​ ​
for more information on this.

​Tx​

**Comment by RSingholia** [comment]
Hi, Thanks for your precious support. 
I have already set the parameter as True for *Continue of error'. Please look at the below parameters of the properties file. please help in resolving this issue.

outputDir=D:\SmartSheetBackup
#continueOnError=true
#zipOutputDir=true
#downloadThreads=10
#allDownloadsDoneTimeout=60

**Comment by avioing** [comment]
the config file details you sent to me indicate that the continueOnError
line is still commented out.  please remove the leading # character and try
again.  tx

**Comment by RSingholia** [comment]
Thanks you so much. The issue has been resolved.
